# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#title: Drake HS Mountain Bike Team
#email: your-email@domain.com
#baseurl: "/Drake2017-jekyll" # the subpath of your site, e.g. /blog
#url: "https://drakemtb.github.io/Drake2017-jekyll" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#markdown: kramdown
# Name of site
name: Drake High School

# Short bio or description
description: Mountain Bike Team

# URL of your avatar or profile pic
avatar: https://raw.githubusercontent.com/DrakeMTB/drakeMTB/gh-pages/images/drakeMTBlogo.png

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: drakemtbdirector@gmail.com
  facebook:
  flickr:
  github: DrakeMTB
  instagram: drake_mtb
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: drakehighschool
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/ironsprings
  googleplus: group/drakemtb

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-67095911-2

url: http://drakemtb.org

# Uncomment if github pages project
# baseurl: "/drakeMTB"

#
# Only adjust flags below for updating Jekyll
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.1.3

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
