# Name of site
name: Drake High School

# Short bio or description
description: Mountain Bike Team

# URL of your avatar or profile pic
avatar: https://raw.githubusercontent.com/DrakeMTB/drakeMTB/gh-pages/images/drakeMTBlogo.png

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: drakemtbmedia@gmail.com
  facebook:
  flickr:
  github: Drake
  instagram: drake_mtb
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: drakehighschool
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/ironsprings
  googleplus: group/drakemtb


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-67095911-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://drakemtb.org

# Uncomment if github pages project
# baseurl: "/drakeMTB"

#
# Only adjust flags below for updating Jekyll
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
